name: lenco_flutter_example
description: Example app for lenco_flutter package

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lenco_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0